### ISSUE TITLE
question about to use this code with Windows Forms

### ISSUE THREAD

**Issue by dg782** [martijn00/MaterialDesignHelpers#1]
Hi,
Is is not an issue just a question.
You did a huge work to convert to Xamarin Android several useful apps from pure Android.
Is it possible (and how to do that) to use this code (and others you did) with Xamarin Forms and Xaml ?
Thanks

**Comment by martijn00** [comment]
You can always create a native renderer, but in general this is a StackOverflow question and doesn't belong here.

**Comment by dg782** [comment]
Sorry to post my question here but I wanted also to know if you have these codes with Windows.Forms and if I had not missed anything. Now I know that you have not.
